[pytest]

#CMD logging (Set warning due to clear cmd output)
log_cli = 1
log_cli_level = INFO
log_cli_date_format = %Y-%m-%d %H:%M:%S
log_cli_format = %(asctime)s |%(levelname)s| |[%(filename)s:%(lineno)d][%(funcName)s]| %(message)s

#Test case naming rules
python_files = test_* *_test test*
python_classes = Test* test*
python_functions = test_* test*

#Recursive discovery rules for test case
norecursedirs = data framework module page log reports tools

markers =
    P1: Priority 1(Cube 官網 網銀 Robo)
    P2: Priority 2(Cube 官網 網銀 Robo)
    P3: Priority 3(Cube 官網 網銀 Robo)
    debug: for debug use
    android: android platform
    ios: ios platform

    positive: 正向
    negative: 負向

    precondition: 前置
    reg: 執行reg

    screenshot: 需檢查截圖
    zh: 中文版
    en: 英文版

    ios:
        personal
        login_ihave
        password
        overview
    android_login
    gmb_login
    ios_login
    gmb_unlock

addopts = --strict-markers --tb=short --clean-alluredir --alluredir=./reports/allure_tmp